name: Deploy

on: 
  workflow_dispatch: {}
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Build
        uses: ./.github/workflows/build_targets
      - name: Zip Artifacts
        uses: papeloto/action-zip@v1
        with:
          files: build/${{ matrix.targetPlatform }}/
          dest: ${{ matrix.targetPlatform }}.zip
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          artifacts: '*.zip'
          bodyFile: release.md
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}    
  
