name: Deploy

on: 
  workflow_dispatch: {}
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy for ${{ matrix.targetPlatform }} 🎮
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
          - Android
          - iOS
          - WebGL
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Restore Library Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - name: Build Targets
        uses: webbertakken/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: build/${{ matrix.targetPlatform }}
      
      - name: Zip Artifacts
        uses: papeloto/action-zip@v1
        with:
          files: build/${{ matrix.targetPlatform }}/
          dest: ${{ matrix.targetPlatform }}.zip
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          artifacts: '*.zip'
          bodyFile: release.md
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy WebGL
        if: ${{ matrix.targetPlatform == 'WebGL' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL
  
